### ISSUE TITLE
Question about testing with other datasets

### ISSUE THREAD

**Issue by quan-li-co** [tata1661/SHINE-EMNLP21#2]
Hi,

Thanks for your work~ 

I have some problems with using other datasets. It seems I can only test with the dataset provided in the repo (Twitter, snippets). Could you please tell me that how to test with other datasets? It seems like I need to do some data preprocessing work to generate some files (pkl, json, etc...) 

Could you please also release the code for the data preprocessing so that I can do some tests with other datasets?

Thanks for your help.

**Comment by tata1661** [comment]
Thanks for the interest! 
I upload the data pre-processing codes and files. Please see README.
