### ISSUE TITLE
load_data

### ISSUE THREAD

**Issue by Lizhaoqing123** [tata1661/SHINE-EMNLP21#5]
请问为什么让每次train40个，并且分成了40个tain，40个valid，剩下的都是test？
如果我使用得数据集已经划分好了train，valid和test数据集，我应该怎么改这部分呢

**Comment by tata1661** [comment]
@Lizhaoqing123 We follow the setting of [HGAT](https://aclanthology.org/D19-1488/).
You can change this number according to your needs. 
You can also learn how to preprocess the data by examining [preprocess](https://github.com/tata1661/SHINE-EMNLP21/tree/master/preprocess) folder.
