### ISSUE TITLE
Has anyone reproduced the results in the paper?

### ISSUE THREAD

**Issue by hahah181292** [tata1661/SHINE-EMNLP21#7]
Has anyone reproduced the results in the paper? According to the parameter Settings in the paper, I run the code, but the result is much lower than wrote in the paper. Could you please tell me whether I made a mistake in setting that led to the decrease of the result.

Below is a screenshot of the parameter Settings and the experimental results run out
![QD7C R~RY}YG$GDE~{Z8FG1](https://user-images.githubusercontent.com/94736343/176330085-31b400e8-bbe0-440c-90a1-6a416452fa00.png)
![58F`%XPN{HB 4}X$F{V74PC](https://user-images.githubusercontent.com/94736343/176330097-72d7340c-fc18-4e2a-bf72-899b482781c7.png)

**Comment by tata1661** [comment]
@hahah181292 Please use the hyperparameters set in the codes. 
The training logs are attached below. 
[twitter.log](https://github.com/tata1661/SHINE-EMNLP21/files/9026508/twitter.log)
[snippets.log](https://github.com/tata1661/SHINE-EMNLP21/files/9026509/snippets.log)

**Comment by hahah181292** [comment]
> @hahah181292 Please use the hyperparameters set in the codes. The training logs are attached below. [twitter.log](https://github.com/tata1661/SHINE-EMNLP21/files/9026508/twitter.log) [snippets.log](https://github.com/tata1661/SHINE-EMNLP21/files/9026509/snippets.log)
Thank you very much for your reply. I ran again according to the parameters in the code, but the result was still not 
[twitter.log](https://github.com/tata1661/SHINE-EMNLP21/files/9028600/twitter.log)
satisfactory. The training log and result parameters are attached below. Could you please send a copy of the relevant parameters? I look forward to your reply, which will be of great help to me.
![JI$@O2BF 5 N61Q8NMI1`PX](https://user-images.githubusercontent.com/94736343/176889110-2e8d9c4d-eee4-4da9-843f-c101d2775898.png)

**Comment by hahah181292** [comment]
> @hahah181292 Please use the hyperparameters set in the codes. The training logs are attached below. [twitter.log](https://github.com/tata1661/SHINE-EMNLP21/files/9026508/twitter.log) [snippets.log](https://github.com/tata1661/SHINE-EMNLP21/files/9026509/snippets.log)


Thank you very much for your reply. I ran again according to the parameters in the code, and the result was still unsatisfactory. Could you please send a copy of the relevant parameters? I look forward to your reply, which will be of great help to me.

Following is the parameters I used in the code and result I got.

![JI$@O2BF 5 N61Q8NMI1`PX](https://user-images.githubusercontent.com/94736343/176889789-90ed18e6-2b56-4d6e-b053-552396f98da8.png)

[twitter.log](https://github.com/tata1661/SHINE-EMNLP21/files/9028619/twitter.log)
